services:
  nordcreds:
    image: "oscarluu/nordcreds:1.0.0"
    cap_add:
      - NET_ADMIN
    sysctls: 
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - ACCESS_TOKEN=${NORD_ACCESS_TOKEN}
